server.port=8080
spring.data.mongodb.uri=mongodb+srv://malphite4266:leesin4266@apirental-car.b0gfz.mongodb.net/test?retryWrites=true&w=majority&appName=APIRental-Car
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
file.upload-dir=../uploads
google.client.id=
google.secret.id=
# JWT secret for development (change for production)
jwt.secret=0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF